[package]
name = 'Quotes'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
[addresses]
my_addr ='0x1081f1c161922255c6f109c53e6ce73c9d6bc7244febc298bb544c67368fa05e'
